export const OTP_CONFIRMATION = 'OTP_CONFIRMATION';
export const OTP_CONFIRMATION_SUCCESS = 'OTP_CONFIRMATION_SUCCESS';
export const OTP_CONFIRMATION_FAIL = 'OTP_CONFIRMATION_FAIL';

export const OTP_EMAIL_CONFIRMATION = 'OTP_EMAIL_CONFIRMATION';
export const OTP_EMAIL_CONFIRMATION_SUCCESS = 'OTP_EMAIL_CONFIRMATION_SUCCESS';
export const OTP_EMAIL_CONFIRMATION_FAIL = 'OTP_EMAIL_CONFIRMATION_FAIL';

export const GET_AVAILABLE_REGIONS = 'GET_AVAILABLE_REGIONS';
export const GET_AVAILABLE_REGIONS_SUCCESS = 'GET_AVAILABLE_REGIONS_SUCCESS';
export const GET_AVAILABLE_REGIONS_FAIL = 'GET_AVAILABLE_REGIONS_FAIL';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAIL = 'GET_DASHBOARD_FAIL';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const SHOW_PROGRESS_DIALOG = 'SHOW_PROGRESS_DIALOG';
export const HIDE_PROGRESS_DIALOG = 'HIDE_PROGRESS_DIALOG';

export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE';
export const GET_EXCHANGE_RATE_SUCCESS = 'GET_EXCHANGE_RATE_SUCCESS';
export const GET_EXCHANGE_RATE_FAIL = 'GET_EXCHANGE_RATE_FAIL';
